_base_: '../_base_/rs.yml'

batch_size: 4
iters: 480000

model:
  type: SegFormer_B1
  num_classes: 4
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/mix_vision_transformer_b1.tar.gz

optimizer:
  _inherited_: False
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  power: 1

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]


